name: Convert Docx to Markdown

on:
  push:
    paths:
      - '*.docx'  # docx 파일의 변경을 감지

permissions:
  contents: write  # GITHUB_TOKEN에 쓰기 권한 부여

jobs:
  convert-docx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
          python -m pip install --upgrade pip
          pip install python-docx pillow

      - name: Convert docx to markdown
        run: python convert_docx_to_md.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          git config --global user.name "${{ env.USER_NAME }}"
          git config --global user.email "${{ env.USER_EMAIL }}"
          git pull origin main  # 원격 저장소의 변경 사항을 가져옴
          git add *.md output_images/*.png
          git commit -m "Update markdown files from docx files"
          git push
